### ISSUE TITLE
Klipper Python3 surpport?

### ISSUE THREAD

**Issue by sjqlwy** [julianschill/klipper-led_effect#47]
Nice work! Does this surpport Klipper Python3?

**Comment by sjqlwy** [comment]
> 
unable to run on Klipper Py3, got error as follows:
TypeError: unsupported operand type(s) for *: 'NoneType' and 'int'
```yaml
mcu 'mcu': Starting serial connect
webhooks client 547976919840: New connection
webhooks client 547976919840: Client info {'program': 'Moonraker', 'version': 'v0.7.1-479-g060ca56'}
Loaded MCU 'mcu' 94 commands (v0.10.0-323-g80492432-dirty-20220421_170315-phicomm / gcc: (15:9-2019-q4-0ubuntu1) 9.2.1 20191025 (release) [ARM/arm-9-branch revision 277599] binutils: (2.34-4ubuntu1+13ubuntu1) 2.34)
MCU 'mcu' config: ADC_MAX=4095 BUS_PINS_i2c1=PB6,PB7 BUS_PINS_i2c1a=PB8,PB9 BUS_PINS_i2c2=PB10,PB11 BUS_PINS_spi1=PA6,PA7,PA5 BUS_PINS_spi1a=PB4,PB5,PB3 BUS_PINS_spi2=PB14,PB15,PB13 BUS_PINS_spi3=PB4,PB5,PB3 CLOCK_FREQ=72000000 MCU=stm32f103xe PWM_MAX=255 RESERVE_PINS_USB=PA11,PA12 STATS_SUMSQ_BASE=256 STEPPER_BOTH_EDGE=1
Sending MCU 'mcu' printer configuration...
Configured MCU 'mcu' (1024 moves)
Unhandled exception during ready callback
Traceback (most recent call last):
  File "/home/pi/klipper/klippy/klippy.py", line 189, in _connect
    cb()
  File "/home/pi/klipper/klippy/extras/led_effect.py", line 376, in _handle_ready
    self.layers.insert(0, layer(handler       = self,
  File "/home/pi/klipper/klippy/extras/led_effect.py", line 754, in __init__
    gradient   = colorArray(self._gradient(self.paletteColors,
  File "/home/pi/klipper/klippy/extras/led_effect.py", line 489, in _gradient
    palette = colorArray(palette[:])
  File "/home/pi/klipper/klippy/extras/led_effect.py", line 29, in __getitem__
    slice(a.start*3, a.stop*3, a.step)))
TypeError: unsupported operand type(s) for *: 'NoneType' and 'int'
Transition to shutdown state: Internal error during ready callback: unsupported operand type(s) for *: 'NoneType' and 'int'
```

**Comment by julianschill** [comment]
Python3 is supported now.
